(part "SLC7649S-121KLC"
    (packageRef "SLC7649S121KLC")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "994-SLC7649S-121KLC")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Coilcraft/SLC7649S-121KLC?qs=zCSbvcPd3pZzvmkyAkuqYA%3D%3D")
    (property "Manufacturer_Name" "COILCRAFT")
    (property "Manufacturer_Part_Number" "SLC7649S-121KLC")
    (property "Description" "Power inductor, shielded, 10% tol, SMT, RoHS")
    (property "Datasheet_Link" "https://www.coilcraft.com/getmedia/0d701ca2-6dd3-4654-9f29-37f6d8a82fc7/slc7649.pdf")
    (property "symbolName1" "SLC7649S-121KLC")
)
